const actions = {
    GET_USER_DETAILS: 'GET_USER_DETAILS',
    GET_CART_ITEMS: 'GET_CART_ITEMS',
    GET_BLOG_ITEMS: 'GET_BLOG_ITEMS',
    GET_BLOG_CONTENT: 'GET_BLOG_CONTENT',
    REMOVE_BLOG_ITEMS: 'REMOVE_BLOG_ITEMS',
    GET_USER_TOKEN: 'GET_USER_TOKEN',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    OPEN_FEEDBACK: 'OPEN_FEEDBACK',
    GET_USER_NAME: 'GET_USER_NAME',
    CLOSE_FEEDBACK: 'CLOSE_FEEDBACK',
    SEND_BLOG_IMAGE: 'SEND_BLOG_IMAGE'
};

export default actions;
